// Generated by gencpp from file wam_srvs/LEDControl.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_LEDCONTROL_H
#define WAM_SRVS_MESSAGE_LEDCONTROL_H

#include <ros/service_traits.h>


#include <wam_srvs/LEDControlRequest.h>
#include <wam_srvs/LEDControlResponse.h>


namespace wam_srvs
{

struct LEDControl
{

typedef LEDControlRequest Request;
typedef LEDControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LEDControl
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::LEDControl > {
  static const char* value()
  {
    return "e4cf4d84661c7dde87aee2c1b97ddf9d";
  }

  static const char* value(const ::wam_srvs::LEDControl&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::LEDControl > {
  static const char* value()
  {
    return "wam_srvs/LEDControl";
  }

  static const char* value(const ::wam_srvs::LEDControl&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::LEDControlRequest> should match
// service_traits::MD5Sum< ::wam_srvs::LEDControl >
template<>
struct MD5Sum< ::wam_srvs::LEDControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::LEDControl >::value();
  }
  static const char* value(const ::wam_srvs::LEDControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::LEDControlRequest> should match
// service_traits::DataType< ::wam_srvs::LEDControl >
template<>
struct DataType< ::wam_srvs::LEDControlRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::LEDControl >::value();
  }
  static const char* value(const ::wam_srvs::LEDControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::LEDControlResponse> should match
// service_traits::MD5Sum< ::wam_srvs::LEDControl >
template<>
struct MD5Sum< ::wam_srvs::LEDControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::LEDControl >::value();
  }
  static const char* value(const ::wam_srvs::LEDControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::LEDControlResponse> should match
// service_traits::DataType< ::wam_srvs::LEDControl >
template<>
struct DataType< ::wam_srvs::LEDControlResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::LEDControl >::value();
  }
  static const char* value(const ::wam_srvs::LEDControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_LEDCONTROL_H
