// Generated by gencpp from file wam_msgs/FtTorques.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_FTTORQUES_H
#define WAM_MSGS_MESSAGE_FTTORQUES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_msgs
{
template <class ContainerAllocator>
struct FtTorques_
{
  typedef FtTorques_<ContainerAllocator> Type;

  FtTorques_()
    : torque()  {
    }
  FtTorques_(const ContainerAllocator& _alloc)
    : torque(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::wam_msgs::FtTorques_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_msgs::FtTorques_<ContainerAllocator> const> ConstPtr;

}; // struct FtTorques_

typedef ::wam_msgs::FtTorques_<std::allocator<void> > FtTorques;

typedef boost::shared_ptr< ::wam_msgs::FtTorques > FtTorquesPtr;
typedef boost::shared_ptr< ::wam_msgs::FtTorques const> FtTorquesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_msgs::FtTorques_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_msgs::FtTorques_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wam_msgs::FtTorques_<ContainerAllocator1> & lhs, const ::wam_msgs::FtTorques_<ContainerAllocator2> & rhs)
{
  return lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wam_msgs::FtTorques_<ContainerAllocator1> & lhs, const ::wam_msgs::FtTorques_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::FtTorques_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::FtTorques_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::FtTorques_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::FtTorques_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::FtTorques_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::FtTorques_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_msgs::FtTorques_<ContainerAllocator> >
{
  static const char* value()
  {
    return "112892c77fa672ef64e426053b200e0d";
  }

  static const char* value(const ::wam_msgs::FtTorques_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x112892c77fa672efULL;
  static const uint64_t static_value2 = 0x64e426053b200e0dULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_msgs::FtTorques_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_msgs/FtTorques";
  }

  static const char* value(const ::wam_msgs::FtTorques_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_msgs::FtTorques_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] torque\n"
;
  }

  static const char* value(const ::wam_msgs::FtTorques_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_msgs::FtTorques_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FtTorques_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_msgs::FtTorques_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_msgs::FtTorques_<ContainerAllocator>& v)
  {
    s << indent << "torque[]" << std::endl;
    for (size_t i = 0; i < v.torque.size(); ++i)
    {
      s << indent << "  torque[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.torque[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_MSGS_MESSAGE_FTTORQUES_H
