# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from wam_msgs/tactilePressureArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import wam_msgs.msg

class tactilePressureArray(genpy.Message):
  _md5sum = "80eca1e412dfc201a84073789556efac"
  _type = "wam_msgs/tactilePressureArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """wam_msgs/tactilePressure[] tactilePressures

================================================================================
MSG: wam_msgs/tactilePressure
float64[] pressure
int32[] normalizedPressure
"""
  __slots__ = ['tactilePressures']
  _slot_types = ['wam_msgs/tactilePressure[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tactilePressures

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(tactilePressureArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tactilePressures is None:
        self.tactilePressures = []
    else:
      self.tactilePressures = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.tactilePressures)
      buff.write(_struct_I.pack(length))
      for val1 in self.tactilePressures:
        length = len(val1.pressure)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.Struct(pattern).pack(*val1.pressure))
        length = len(val1.normalizedPressure)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.normalizedPressure))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tactilePressures is None:
        self.tactilePressures = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tactilePressures = []
      for i in range(0, length):
        val1 = wam_msgs.msg.tactilePressure()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.pressure = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.normalizedPressure = s.unpack(str[start:end])
        self.tactilePressures.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.tactilePressures)
      buff.write(_struct_I.pack(length))
      for val1 in self.tactilePressures:
        length = len(val1.pressure)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.pressure.tostring())
        length = len(val1.normalizedPressure)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.normalizedPressure.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tactilePressures is None:
        self.tactilePressures = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tactilePressures = []
      for i in range(0, length):
        val1 = wam_msgs.msg.tactilePressure()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.pressure = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.normalizedPressure = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.tactilePressures.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
