(cl:defpackage wam_msgs-msg
  (:use )
  (:export
   "<ENDPOINTSTATE>"
   "ENDPOINTSTATE"
   "<FTTORQUES>"
   "FTTORQUES"
   "<RTCARTPOS>"
   "RTCARTPOS"
   "<RTCARTVEL>"
   "RTCARTVEL"
   "<RTJOINTPOS>"
   "RTJOINTPOS"
   "<RTJOINTVEL>"
   "RTJOINTVEL"
   "<RTORTNPOS>"
   "RTORTNPOS"
   "<RTORTNVEL>"
   "RTORTNVEL"
   "<RTPOSE>"
   "RTPOSE"
   "<TACTILEPRESSURE>"
   "TACTILEPRESSURE"
   "<TACTILEPRESSUREARRAY>"
   "TACTILEPRESSUREARRAY"
  ))

